---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: '@babel/eslint-parser'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'prettier'

rules: { no-console: 0, import/extensions: 0, no-param-reassign: 0, eslint-disable-next-line: 0 }
